#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.peditx >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.peditx=/luci-static/peditx
		set luci.main.mediaurlbase=/luci-static/peditx
		commit luci
	EOF
fi

exit 0
